In [111]:
import pandas as pd

## For NMR data

1) Find NMR files from Biological Magnetic Resonance Data Bank (https://bmrb.io/). E.g. vanillin (https://bmrb.io/metabolomics/mol_summary/show_data.php?id=bmse000343&whichTab=1) or Human Metabolome Database (https://www.hmdb.ca/)

3) Download the .zip file under Time Domain Data. Within the file, there should be bmseXXXXXXX/nmr/set01/1H, and the like. For Topspin to recognize the file, need to rename to just a number (e.g. 1H become 1, 13C becomes C).

4) Open the numbered file in Topspin. Process as normal, importantly, input the command "convbin2asc". This is create as ascii-spec.txt file in the same directory. The file should have 4 columns: Point number, Intensity, Chemical Shift (Hz), Chemical Shift (ppm). (https://u-of-o-nmr-facility.blogspot.com/2014/02/getting-xy-ascii-data-from-topspin.html)

6) Rename the .txt file to a .csv file. In excel, truncate to just "Chemical Shift (ppm)" and "Intensity" columns, add header row with those labels.

In [175]:
nmrH = pd.read_csv('5/chloroxylenol_HNMR.csv')
nH = 8.2
nmrH

      Chemical Shift (ppm)     Intensity
0                10.930455  0.000000e+00
1                10.910937 -8.014420e-16
2                10.891419 -1.006140e-16
3                10.871901 -1.099810e-15
4                10.852384  3.998540e-15
...                    ...           ...
1221             -0.146001  5.179880e-14
1222             -0.165519 -4.999990e-14
1223             -0.185037  4.890010e-14
1224             -0.204555 -1.350140e-14
1225             -0.224073 -2.050100e-14

[1226 rows x 2 columns]

In [176]:
nmrH1 = round(nmrH['Chemical Shift (ppm)'],3)
nmrH['Chemical Shift (ppm)']=nmrH1
nmrH2 = nmrH.groupby('Chemical Shift (ppm)')['Intensity'].mean().reset_index()
nmrH3 = round(nmrH2['Intensity']/nmrH2['Intensity'].max()*100,2)
nmrH2['Intensity'] = nmrH3
nmrH4 = nmrH2[abs(nmrH2['Intensity']) > -0.1]

nmrH5 = nmrH4['Intensity'].cumsum()
nmrH5 = round(nH - nmrH5/nmrH5.max()*nH,2)
nmrH4['Integral'] = nmrH5
nmrH4

     Chemical Shift (ppm)  Intensity  Integral
0                  -0.224       -0.0       8.2
1                  -0.205       -0.0       8.2
2                  -0.185        0.0       8.2
3                  -0.166       -0.0       8.2
4                  -0.146        0.0       8.2
..                    ...        ...       ...
613                10.852        0.0       0.0
614                10.872       -0.0       0.0
615                10.891       -0.0       0.0
616                10.911       -0.0       0.0
617                10.930        0.0       0.0

[618 rows x 3 columns]

In [177]:
nmrH4.to_csv('5/5_HNMR.csv',index=False)

In [172]:
nmrC = pd.read_csv('5/chloroxylenol_CNMR.csv')
nmrC

      Chemical Shift (ppm)  Intensity
0               199.711895   0.001526
1               199.354427   0.001526
2               198.996958   0.001526
3               198.639489   0.001526
4               198.282021   0.001526
...                    ...        ...
1374             -2.794114   0.001526
1375             -3.151583   0.001526
1376             -3.509052   0.001526
1377             -3.866520   0.001526
1378             -4.223989   0.001526

[1379 rows x 2 columns]

In [173]:
nmrC1 = round(nmrC['Chemical Shift (ppm)'],3)
nmrC['Chemical Shift (ppm)']=nmrC1
nmrC2 = nmrC.groupby('Chemical Shift (ppm)')['Intensity'].mean().reset_index()
nmrC3 = round(nmrC2['Intensity']/nmrC2['Intensity'].max()*100,2)
nmrC2['Intensity'] = nmrC3
nmrC4 = nmrC2[abs(nmrC2['Intensity']) > -0.1]
nmrC4

      Chemical Shift (ppm)  Intensity
0                   -4.224        0.0
1                   -3.867        0.0
2                   -3.509        0.0
3                   -3.152        0.0
4                   -2.794        0.0
...                    ...        ...
1068               198.282        0.0
1069               198.639        0.0
1070               198.997        0.0
1071               199.354        0.0
1072               199.712        0.0

[1073 rows x 2 columns]

In [174]:
nmrC4.to_csv('5/5_CNMR.csv',index=False)

## For MS Data

1) Find compound in https://sdbs.db.aist.go.jp/
2) Navigate to the MS data. There should be a button "peak data" below the spectrum itself.
3) Copy and paste the MS peaks into an excel file. Add header rows that specify "m/z" and "Intensity"
4) Save excel file as .csv file

In [147]:
ms = pd.read_csv('5/chloroxylenol_MS.csv')
print(ms)

    m/z  Intensity
0    27        3.6
1    37        1.1
2    38        1.9
3    39        9.0
4    40        1.1
5    41        2.7
6    43        1.8
7    45        1.9
8    46        1.2
9    50        3.9
10   51        9.5
11   52        2.8
12   53        3.7
13   55        2.7
14   59        2.2
15   60        1.0
16   61        1.1
17   62        1.8
18   63        4.1
19   64        1.2
20   65        9.6
21   66        1.4
22   67        1.5
23   73        1.2
24   74        1.4
25   75        2.2
26   77       17.2
27   78        4.1
28   79        1.3
29   87        1.3
30   89        1.9
31   91       26.8
32   92        3.9
33   93        3.7
34   94        1.4
35  103        3.1
36  105        1.4
37  119        3.6
38  120        3.9
39  121      100.0
40  122        9.4
41  127        2.8
42  129        1.0
43  141        3.9
44  143        1.2
45  155        7.2
46  156       89.2
47  157       10.3
48  158       28.2
49  159        2.8

In [148]:
ms1=[]
ms2=[]
for i in range(ms['m/z'].min()-5,ms['m/z'].max()+10):
    ms1.append(i)
    if i in ms['m/z'].to_list():
        ms2.append(ms['Intensity'].loc[list(ms['m/z']).index(i)])
    else:
        ms2.append(0)

ms3=pd.DataFrame({'m/z':ms1,'Intensity':ms2})
ms3

     m/z  Intensity
0     22        0.0
1     23        0.0
2     24        0.0
3     25        0.0
4     26        0.0
..   ...        ...
142  164        0.0
143  165        0.0
144  166        0.0
145  167        0.0
146  168        0.0

[147 rows x 2 columns]

In [149]:
ms3.to_csv('5/5_MS.csv',index=False)

## For IR Data

1) Find compound in NIST Chemistry Webbook: https://webbook.nist.gov/chemistry/
2) Find IR spectrum and download JCAMP-DX file.
3) Import file (it is a tab separated value file) into excel, reformat with two header columns "Wavenumber (cm-1)" and "Transmittance (%)". The files might be in wavelength (um) and should be converted to the appropriate unit in excel first.
4) Save as a csv file

In [150]:
ir = pd.read_csv('5/5_IR.csv')
ir

      Wavenumber (cm-1)  Intensity
0           3981.708314  81.591650
1           3965.765898  81.735420
2           3949.819218  82.009091
3           3933.869125  82.386684
4           3917.923297  82.634376
...                 ...        ...
1336         435.131339  94.984905
1337         419.193615  94.985783
1338         403.252052  95.103572
1339         387.321578  94.883616
1340         372.730594  94.318048

[1341 rows x 2 columns]

In [35]:
data = pd.DataFrame({'x': ['A', 'B', 'C', 'D', 'E'],
                     'y': [5, 3, 6, 7, 2]})
data

   x  y
0  A  5
1  B  3
2  C  6
3  D  7
4  E  2